# Generated by Django 3.1 on 2022-07-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskApp', '0004_auto_20220716_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(blank=True, upload_to='problems', verbose_name='Photo'),
        ),
    ]
