# Generated by Django 3.1 on 2022-07-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskApp', '0006_auto_20220716_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(null=True, upload_to='problems', verbose_name='Photo'),
        ),
    ]
