# Generated by Django 3.1 on 2022-07-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdeskApp', '0007_auto_20220716_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(upload_to='problems', verbose_name='Photo'),
        ),
    ]
